services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    hostname: filebrowser_Evaru
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - /srv/docker/filebrowser/config:/config
      - /srv/docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/almacenamiento/jellyfin:/srv
    networks:
      - media_net

networks:
  media_net:
    external: true
